<?php

use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Dashboard\ArtifactDownloadController;
use App\Http\Controllers\Dashboard\ArtifactRetentionRunController;
use App\Http\Controllers\Dashboard\ArtifactsIndexController;
use App\Http\Controllers\Dashboard\AuditExportStoreController;
use App\Http\Controllers\Dashboard\Api\DashboardAdminController;
use App\Http\Controllers\Dashboard\Api\DashboardHadesController;
use App\Http\Controllers\Dashboard\Api\DashboardAiAgentController;
use App\Http\Controllers\Dashboard\Api\DashboardAgentWorkController;
use App\Http\Controllers\Dashboard\Api\DashboardBackupController;
use App\Http\Controllers\Dashboard\Api\DashboardMemoryController;
use App\Http\Controllers\Dashboard\Api\DashboardProjectLifecycleController;
use App\Http\Controllers\Dashboard\Api\DashboardProjectRepositoryController;
use App\Http\Controllers\Dashboard\Api\DashboardResourceController;
use App\Http\Controllers\Dashboard\Api\DashboardSystemController;
use App\Http\Controllers\Dashboard\Api\DashboardTaskAttachmentController;
use App\Http\Controllers\Dashboard\Api\AssistantSuggestionController;
use App\Http\Controllers\Dashboard\Api\BacklogTriageController;
use App\Http\Controllers\Dashboard\Api\TaskClarifierController;
use App\Http\Controllers\Dashboard\AiAgentsIndexController;
use App\Http\Controllers\Dashboard\AuthController as DashboardAuthController;
use App\Http\Controllers\Dashboard\GraphShowController;
use App\Http\Controllers\Dashboard\KanbanController;
use App\Http\Controllers\Dashboard\PluginTokenController;
use App\Http\Controllers\Dashboard\ProjectShowController;
use App\Http\Controllers\Dashboard\Quality\QualityController;
use App\Http\Controllers\Dashboard\RunsIndexController;
use App\Http\Controllers\Dashboard\RunRetryImportController;
use App\Http\Controllers\Dashboard\RunReviewController;
use App\Http\Controllers\Dashboard\RunShowController;
use App\Http\Controllers\Dashboard\TaskShowController;
use App\Http\Controllers\Dashboard\SystemShowController;
use App\Http\Controllers\Dashboard\WikiIndexController;
use App\Http\Controllers\Dashboard\WikiShowController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/kanban');

Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store']);
});

Route::prefix('/api/dashboard')->group(function () {
    Route::post('/login', [DashboardAuthController::class, 'login']);
});

Route::middleware('auth')->group(function () {
    Route::prefix('/api/dashboard')->group(function () {
        Route::get('/me', [DashboardAuthController::class, 'me']);
        Route::post('/logout', [DashboardAuthController::class, 'logout']);
        Route::get('/overview', [DashboardResourceController::class, 'overview']);
        Route::get('/kanban', [DashboardResourceController::class, 'kanban']);
        Route::post('/projects/{project}/tasks', [DashboardResourceController::class, 'storeProjectTask']);
        Route::patch('/tasks/{task}', [DashboardResourceController::class, 'updateTask']);
        Route::post('/tasks/{task}/assistant/clarify', TaskClarifierController::class);
        Route::patch('/assistant-suggestions/{suggestion}', [AssistantSuggestionController::class, 'update']);
        Route::post('/assistant-suggestions/{suggestion}/apply', [AssistantSuggestionController::class, 'apply']);
        Route::post('/tasks/{task}/attachments', [DashboardTaskAttachmentController::class, 'store']);
        Route::delete('/tasks/{task}/attachments/{attachment}', [DashboardTaskAttachmentController::class, 'destroy']);
        Route::get('/tasks/{task}/attachments/{attachment}/download', [DashboardTaskAttachmentController::class, 'download']);
        Route::get('/tasks/{task}', [DashboardResourceController::class, 'task']);
        Route::get('/projects', [DashboardResourceController::class, 'projects']);
        Route::post('/projects', [DashboardResourceController::class, 'createProject']);
        Route::get('/projects/{project}', [DashboardResourceController::class, 'project']);
        Route::patch('/projects/{project}', [DashboardResourceController::class, 'updateProject']);
        Route::post('/projects/{project}/repositories', [DashboardProjectRepositoryController::class, 'store']);
        Route::get('/projects/{project}/memory', [DashboardMemoryController::class, 'index']);
        Route::post('/projects/{project}/memory', [DashboardMemoryController::class, 'store']);
        Route::get('/projects/{project}/agent-work', [DashboardAgentWorkController::class, 'index']);
        Route::post('/projects/{project}/agent-work', [DashboardAgentWorkController::class, 'store']);
        Route::post('/agent-work/{workItem}/cancel', [DashboardAgentWorkController::class, 'cancel']);
        Route::post('/projects/{project}/assistant/backlog-triage', BacklogTriageController::class);
        Route::post('/projects/{project}/archive', [DashboardProjectLifecycleController::class, 'archive']);
        Route::post('/projects/{project}/restore', [DashboardProjectLifecycleController::class, 'restore']);
        Route::post('/projects/{project}/delete', [DashboardProjectLifecycleController::class, 'delete']);
        Route::get('/projects/{project}/kanban', [DashboardResourceController::class, 'projectKanban']);
        Route::get('/projects/{project}/runs', [DashboardResourceController::class, 'projectRuns']);
        Route::get('/projects/{project}/wiki', [DashboardResourceController::class, 'projectWiki']);
        Route::get('/projects/{project}/artifacts', [DashboardResourceController::class, 'projectArtifacts']);
        Route::get('/runs', [DashboardResourceController::class, 'runs']);
        Route::get('/runs/{run}', [DashboardResourceController::class, 'run']);
        Route::post('/runs/{run}/retry-import', [DashboardResourceController::class, 'retryImport']);
        Route::post('/runs/{run}/review', [DashboardResourceController::class, 'review']);
        Route::get('/wiki', [DashboardResourceController::class, 'wiki']);
        Route::get('/wiki/pages/{page}', [DashboardResourceController::class, 'wikiPage']);
        Route::get('/graph', [DashboardResourceController::class, 'graph']);
        Route::get('/artifacts', [DashboardResourceController::class, 'artifacts']);
        Route::get('/runs/{run}/artifacts/{artifact}/download', [DashboardResourceController::class, 'downloadArtifact']);
        Route::get('/admin/plugin-tokens', [DashboardAdminController::class, 'tokens']);
        Route::post('/admin/plugin-tokens', [DashboardAdminController::class, 'createToken']);
        Route::post('/admin/plugin-tokens/{token}/rotate', [DashboardAdminController::class, 'rotateToken']);
        Route::delete('/admin/plugin-tokens/{token}', [DashboardAdminController::class, 'revokeToken']);
        Route::get('/admin/hades', [DashboardHadesController::class, 'index']);
        Route::post('/admin/hades/bootstrap-tokens', [DashboardHadesController::class, 'createBootstrapToken']);
        Route::delete('/admin/hades/bootstrap-tokens/{token}', [DashboardHadesController::class, 'revokeBootstrapToken']);
        Route::post('/admin/hades/jobs', [DashboardHadesController::class, 'createJob']);
        Route::post('/admin/hades/memory-proposals/{proposal}/review', [DashboardHadesController::class, 'reviewMemoryProposal']);
        Route::get('/admin/devices', [DashboardAdminController::class, 'devices']);
        Route::delete('/admin/devices/{device}', [DashboardAdminController::class, 'revokeDevice']);
        Route::get('/admin/ai-agents', [DashboardAiAgentController::class, 'index']);
        Route::put('/admin/ai-model-providers/{provider}', [DashboardAiAgentController::class, 'updateProvider']);
        Route::put('/admin/ai-model-profiles/{profile}', [DashboardAiAgentController::class, 'updateModelProfile']);
        Route::patch('/admin/ai-agent-profiles/{agent}', [DashboardAiAgentController::class, 'updateAgentProfile']);
        Route::get('/system', [DashboardSystemController::class, 'show']);
        Route::post('/system/artifact-retention', [DashboardSystemController::class, 'retention']);
        Route::post('/system/audit-exports', [DashboardSystemController::class, 'auditExport']);
        Route::get('/system/backups/readiness', [DashboardBackupController::class, 'readiness']);
        Route::post('/system/backups/export', [DashboardBackupController::class, 'export']);
        Route::get('/system/backups/{backup}/download', [DashboardBackupController::class, 'download']);
        Route::post('/system/backups/validate', [DashboardBackupController::class, 'validateBundle']);
    });
    Route::get('/kanban', KanbanController::class);
    Route::get('/artifacts', ArtifactsIndexController::class);
    Route::get('/graph', GraphShowController::class);
    Route::get('/projects/{project}', ProjectShowController::class);
    Route::get('/runs', RunsIndexController::class);
    Route::get('/runs/{run}', RunShowController::class);
    Route::get('/system', SystemShowController::class);
    Route::post('/system/artifact-retention', ArtifactRetentionRunController::class);
    Route::post('/system/audit-exports', AuditExportStoreController::class);
    Route::get('/tasks/{task}', TaskShowController::class);
    Route::get('/wiki', WikiIndexController::class);
    Route::get('/wiki/pages/{page}', WikiShowController::class);
    Route::post('/runs/{run}/retry-import', RunRetryImportController::class);
    Route::post('/runs/{run}/review', RunReviewController::class);
    Route::get('/runs/{run}/artifacts/{artifact}/download', ArtifactDownloadController::class);
    Route::prefix('/api/dashboard/quality')->group(function () {
        Route::get('/overview', [QualityController::class, 'overview']);
        Route::get('/current-state', [QualityController::class, 'currentState']);
        Route::get('/reports', [QualityController::class, 'reports']);
        Route::get('/route-inventory', [QualityController::class, 'routeInventory']);
        Route::get('/route-smoke', [QualityController::class, 'routeSmoke']);
        Route::get('/gates/{gate}', [QualityController::class, 'gate']);
        Route::get('/roadmap', [QualityController::class, 'roadmap']);
        Route::post('/runs', [QualityController::class, 'run']);
    });
    Route::get('/admin/plugin-tokens', [PluginTokenController::class, 'index']);
    Route::post('/admin/plugin-tokens', [PluginTokenController::class, 'store']);
    Route::post('/admin/plugin-tokens/{token}/rotate', [PluginTokenController::class, 'rotate']);
    Route::delete('/admin/plugin-tokens/{token}', [PluginTokenController::class, 'destroy']);
    Route::delete('/admin/devices/{device}', [PluginTokenController::class, 'revokeDevice']);
    Route::get('/admin/ai-agents', AiAgentsIndexController::class);
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy']);
});
